# Generated by Django 5.2.4 on 2025-09-12 05:39

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('user', '사용자')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('sales_diary_company_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='영업일지 회사코드')),
                ('company_code_sm', models.CharField(blank=True, max_length=50, null=True, verbose_name='SM 회사코드')),
                ('company_code_sap', models.CharField(blank=True, max_length=50, null=True, verbose_name='SAP 회사코드')),
                ('company_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='회사유형')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='설립일')),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='주소')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자 연락처')),
                ('main_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표전화')),
                ('distribution_type_sap', models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP 유통유형')),
                ('industry_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='업종명')),
                ('main_product', models.CharField(blank=True, max_length=200, null=True, verbose_name='주요제품')),
                ('transaction_start_date', models.DateField(blank=True, null=True, verbose_name='거래시작일')),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True, verbose_name='결제조건')),
                ('customer_classification', models.CharField(blank=True, max_length=50, null=True, verbose_name='고객분류')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='영업 사원')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사들',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.DateField(verbose_name='결산년도')),
                ('total_assets', models.BigIntegerField(verbose_name='총자산')),
                ('capital', models.BigIntegerField(verbose_name='자본금')),
                ('total_equity', models.BigIntegerField(verbose_name='자본총계')),
                ('revenue', models.BigIntegerField(verbose_name='매출액')),
                ('operating_income', models.BigIntegerField(verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(verbose_name='당기순이익')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statuses', to='myapi.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '회사매출현황',
                'verbose_name_plural': '회사매출현황들',
                'db_table': 'company_financial_status',
                'ordering': ['-fiscal_year', 'company'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('visitDate', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('products', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('company_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='myapi.company')),
            ],
        ),
    ]
