# Generated by Django 5.2.4 on 2025-07-15 01:46

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sapCode', models.CharField(max_length=20)),
                ('smCode', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=50)),
                ('managerPhone', models.CharField(max_length=20)),
                ('establishedDate', models.DateField()),
                ('contractDate', models.DateField()),
                ('paymentTerms', models.CharField(max_length=100)),
                ('customerType', models.CharField(max_length=20)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('monthlySales', models.BigIntegerField()),
                ('lastContact', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('companyCode', models.CharField(max_length=20)),
                ('contactType', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('user', '사용자')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
