# Generated by Django 5.2.4 on 2025-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sapCode', models.CharField(max_length=20)),
                ('smCode', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=50)),
                ('managerPhone', models.CharField(max_length=20)),
                ('establishedDate', models.DateField()),
                ('contractDate', models.DateField()),
                ('paymentTerms', models.CharField(max_length=100)),
                ('customerType', models.CharField(max_length=20)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('monthlySales', models.BigIntegerField()),
                ('lastContact', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('companyCode', models.CharField(max_length=20)),
                ('contactType', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
