# Generated by Django 5.2.4 on 2025-09-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='products',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='소재지'),
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사용품목'),
        ),
    ]
