# Generated by Django 5.2.4 on 2025-07-15 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_report_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='summary',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='companyCode',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='visitDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='contactType',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='company_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='myapi.company'),
        ),
        migrations.AddField(
            model_name='report',
            name='team',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
