# Generated by Django 5.2.4 on 2025-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_report_location_remove_report_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='products',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
