# Generated by Django 5.2.4 on 2025-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_report_location_report_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, choices=[('수도권', '수도권'), ('충청권', '충청권'), ('강원권', '강원권'), ('경상권', '경상권'), ('호남권', '호남권'), ('기타', '기타')], max_length=10, null=True, verbose_name='소재지'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, choices=[('수도권', '수도권'), ('충청권', '충청권'), ('강원권', '강원권'), ('경상권', '경상권'), ('호남권', '호남권'), ('기타', '기타')], max_length=10, null=True),
        ),
    ]
