# Generated by Django 5.2.4 on 2025-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_summary_report_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '회사', 'verbose_name_plural': '회사들'},
        ),
        migrations.AddField(
            model_name='company',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_code_sap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SAP 회사코드'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_code_sm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SM 회사코드'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=1, max_length=200, verbose_name='회사명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='회사유형'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자 연락처'),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_classification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='고객분류'),
        ),
        migrations.AddField(
            model_name='company',
            name='distribution_type_sap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP 유통유형'),
        ),
        migrations.AddField(
            model_name='company',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='설립일'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='업종명'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='대표전화'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_product',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주요제품'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결제조건'),
        ),
        migrations.AddField(
            model_name='company',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_diary_company_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='영업일지 회사코드'),
        ),
        migrations.AddField(
            model_name='company',
            name='transaction_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='거래시작일'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contractDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='customerType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='establishedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='lastContact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='managerPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='monthlySales',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='paymentTerms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sapCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='smCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='웹사이트'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
