# Generated by Django 5.2.4 on 2025-09-29 07:27

from django.db import migrations


def update_location_data(apps, schema_editor):
    """기존 경상권 데이터를 영남권으로 변경"""
    Company = apps.get_model('myapi', 'Company')
    Report = apps.get_model('myapi', 'Report')
    
    # Company 테이블에서 경상권을 영남권으로 변경
    Company.objects.filter(location='경상권').update(location='영남권')
    
    # Report 테이블에서 경상권을 영남권으로 변경
    Report.objects.filter(location='경상권').update(location='영남권')


def reverse_location_data(apps, schema_editor):
    """마이그레이션 되돌리기 (영남권을 경상권으로 다시 변경)"""
    Company = apps.get_model('myapi', 'Company')
    Report = apps.get_model('myapi', 'Report')
    
    # Company 테이블에서 영남권을 경상권으로 변경
    Company.objects.filter(location='영남권').update(location='경상권')
    
    # Report 테이블에서 영남권을 경상권으로 변경
    Report.objects.filter(location='영남권').update(location='경상권')


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_company_location_alter_report_location'),
    ]

    operations = [
        migrations.RunPython(update_location_data, reverse_location_data),
    ]
