# Generated by Django 5.2.4 on 2025-07-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_company_options_company_ceo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contractDate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='customerType',
        ),
        migrations.RemoveField(
            model_name='company',
            name='establishedDate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lastContact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='company',
            name='managerPhone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='monthlySales',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='paymentTerms',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sapCode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='smCode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
