# Generated by Django 5.2.4 on 2025-09-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20250929_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, choices=[('수도권', '수도권'), ('충청권', '충청권'), ('강원권', '강원권'), ('영남권', '영남권'), ('호남권', '호남권'), ('기타', '기타')], max_length=10, null=True, verbose_name='소재지'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, choices=[('수도권', '수도권'), ('충청권', '충청권'), ('강원권', '강원권'), ('영남권', '영남권'), ('호남권', '호남권'), ('기타', '기타')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('매출일자', models.DateField(verbose_name='매출일자')),
                ('코드', models.CharField(blank=True, max_length=50, null=True, verbose_name='코드')),
                ('거래처명', models.CharField(max_length=200, verbose_name='거래처명')),
                ('매출부서', models.CharField(blank=True, max_length=100, null=True, verbose_name='매출부서')),
                ('매출담당자', models.CharField(blank=True, max_length=100, null=True, verbose_name='매출담당자')),
                ('유통형태', models.CharField(blank=True, max_length=100, null=True, verbose_name='유통형태')),
                ('상품코드', models.CharField(blank=True, max_length=100, null=True, verbose_name='상품코드')),
                ('상품명', models.CharField(blank=True, max_length=200, null=True, verbose_name='상품명')),
                ('브랜드', models.CharField(blank=True, max_length=100, null=True, verbose_name='브랜드')),
                ('축종', models.CharField(blank=True, max_length=100, null=True, verbose_name='축종')),
                ('부위', models.CharField(blank=True, max_length=100, null=True, verbose_name='부위')),
                ('원산지', models.CharField(blank=True, max_length=100, null=True, verbose_name='원산지')),
                ('축종_부위', models.CharField(blank=True, max_length=100, null=True, verbose_name='축종-부위')),
                ('원산지_축종', models.CharField(blank=True, max_length=100, null=True, verbose_name='원산지')),
                ('등급', models.CharField(blank=True, max_length=50, null=True, verbose_name='등급')),
                ('Box', models.IntegerField(blank=True, null=True, verbose_name='Box')),
                ('중량_Kg', models.FloatField(blank=True, null=True, verbose_name='중량(Kg)')),
                ('매출단가', models.IntegerField(blank=True, null=True, verbose_name='매출단가')),
                ('매출금액', models.BigIntegerField(verbose_name='매출금액')),
                ('매출이익', models.BigIntegerField(blank=True, null=True, verbose_name='매출이익')),
                ('이익율', models.FloatField(blank=True, null=True, verbose_name='이익율')),
                ('매입처', models.CharField(blank=True, max_length=200, null=True, verbose_name='매입 처')),
                ('매입일자', models.DateField(blank=True, null=True, verbose_name='매입일자')),
                ('재고보유일', models.IntegerField(blank=True, null=True, verbose_name='재고보유일')),
                ('수입로컬', models.CharField(blank=True, max_length=20, null=True, verbose_name='수입/로컬')),
                ('이관재고여부', models.CharField(blank=True, max_length=20, null=True, verbose_name='이관재고 여부')),
                ('담당자', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자')),
                ('매입단가', models.IntegerField(blank=True, null=True, verbose_name='매입단가')),
                ('매입금액', models.BigIntegerField(blank=True, null=True, verbose_name='매입금액')),
                ('지점명', models.CharField(blank=True, max_length=100, null=True, verbose_name='지점명')),
                ('매출비고', models.TextField(blank=True, null=True, verbose_name='매출비고')),
                ('매입비고', models.TextField(blank=True, null=True, verbose_name='매입비고')),
                ('이력번호', models.CharField(blank=True, max_length=100, null=True, verbose_name='이력번호')),
                ('BL번호', models.CharField(blank=True, max_length=100, null=True, verbose_name='B/L번호(도체번호)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('company_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_data', to='myapi.company', verbose_name='연결된 회사')),
            ],
            options={
                'verbose_name': '매출 데이터',
                'verbose_name_plural': '매출 데이터들',
                'db_table': 'sales_data',
                'ordering': ['-매출일자', '거래처명'],
            },
        ),
    ]
