# Generated by Django 5.2.4 on 2025-10-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_company_location_alter_report_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
    ]
