# Generated by Django 5.2.4 on 2025-07-24 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_add_company_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='영업 사원'),
        ),
    ]
