# Generated by Django 5.2.4 on 2025-07-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_company_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.DateField(verbose_name='결산년도')),
                ('total_assets', models.BigIntegerField(verbose_name='총자산')),
                ('capital', models.BigIntegerField(verbose_name='자본금')),
                ('total_equity', models.BigIntegerField(verbose_name='자본총계')),
                ('revenue', models.BigIntegerField(verbose_name='매출액')),
                ('operating_income', models.BigIntegerField(verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(verbose_name='당기순이익')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statuses', to='myapi.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '회사매출현황',
                'verbose_name_plural': '회사매출현황들',
                'db_table': 'company_financial_status',
            },
        ),
    ]
