# Generated by Django 5.2.4 on 2025-10-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_remove_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시/구'),
        ),
    ]
