# Generated by Django 5.2.4 on 2025-07-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_companyfinancialstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfinancialstatus',
            options={'ordering': ['-fiscal_year', 'company'], 'verbose_name': '회사매출현황', 'verbose_name_plural': '회사매출현황들'},
        ),
    ]
