# Generated by Django 5.2.4 on 2025-10-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_company_city_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='사용품목'),
        ),
        migrations.AlterField(
            model_name='report',
            name='products',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
