# Generated by Django 5.2.4 on 2025-10-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alter_company_products_alter_report_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='사용품목'),
        ),
        migrations.AlterField(
            model_name='report',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
