# Generated by Django 5.2.4 on 2025-10-29 07:26

from django.db import migrations, models


def safe_remove_fields(apps, schema_editor):
    """존재하는 필드만 제거"""
    with schema_editor.connection.cursor() as cursor:
        fields_to_check = [
            'COMPANY_CODE_SM', 'ID', 'LOCATION', 'MAIN_PRODUCT', 
            'SALES_DIARY_COMPANY_CODE', 'USERNAME_ID'
        ]
        for field_name in fields_to_check:
            try:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_tab_columns 
                    WHERE table_name = 'COMPANIES' AND column_name = :col_name
                """, {'col_name': field_name})
                exists = cursor.fetchone()[0] > 0
                if exists:
                    cursor.execute(f'ALTER TABLE "COMPANIES" DROP COLUMN "{field_name}"')
            except Exception:
                pass


def reverse_remove_fields(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_set_company_code_as_primary_key'),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_fields,
            reverse_code=reverse_remove_fields
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code_sap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SAP거래처코드'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='거래처 담당자'),
        ),
        migrations.AlterField(
            model_name='company',
            name='distribution_type_sap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='유통형태'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='본사 주소'),
        ),
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='주요제품'),
        ),
        migrations.AlterField(
            model_name='company',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='참고사항'),
        ),
    ]
