# Generated by Django 5.2.4 on 2025-10-30 00:58

from django.db import migrations


def migrate_report_data(apps, schema_editor):
    """
    기존 영업일지 데이터를 새로운 필드 구조에 맞게 업데이트
    - author_name: author.name에서 가져오기
    - author_department: author.department 또는 기존 team 필드에서 가져오기
    - company_name: company_obj.company_name 또는 company 필드에서 가져오기
    - company_city_district: company_obj.city_district에서 가져오기
    """
    Report = apps.get_model('myapi', 'Report')
    
    for report in Report.objects.all():
        # 작성자 정보 업데이트
        if report.author:
            if not report.author_name:
                report.author_name = report.author.name or ''
            if not report.author_department:
                report.author_department = report.author.department or ''
                # 기존 team 필드가 있으면 사용
                if hasattr(report, 'team') and report.team and not report.author_department:
                    report.author_department = report.team
        
        # 회사 정보 업데이트
        if report.company_obj:
            if not report.company_name:
                report.company_name = report.company_obj.company_name or ''
            if not report.company_city_district:
                report.company_city_district = report.company_obj.city_district or ''
        elif hasattr(report, 'company') and (getattr(report, 'company') and not report.company_name):
            # company_obj가 없지만 과거 company 필드에 값이 있는 경우
            report.company_name = getattr(report, 'company')
        
        report.save()


def reverse_migrate_report_data(apps, schema_editor):
    """마이그레이션 롤백 시 실행 (필요한 경우)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        # 스키마 변경(필드 추가)이 끝난 후 데이터 마이그레이션을 수행해야 함
        ('myapi', '0017_alter_report_options_remove_company_company_code_sm_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_report_data, reverse_migrate_report_data),
    ]
