# Generated by Django 5.2.4 on 2025-10-30 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_fix_sap_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '영업일지', 'verbose_name_plural': '영업일지들'},
        ),
        # 이미 존재하지 않을 수 있는 Company의 과거 필드 제거 단계는 생략 (운영 DB 호환)
        migrations.RemoveField(
            model_name='report',
            name='team',
        ),
        migrations.AddField(
            model_name='report',
            name='author_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='팀명'),
        ),
        migrations.AddField(
            model_name='report',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자명'),
        ),
        migrations.AddField(
            model_name='report',
            name='company_city_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소재지(시/구)'),
        ),
        migrations.AddField(
            model_name='report',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='회사명'),
        ),
        migrations.AddField(
            model_name='report',
            name='sales_stage',
            field=models.CharField(blank=True, choices=[('초기 컨택', '초기 컨택'), ('협상 진행(니즈 파악)', '협상 진행(니즈 파악)'), ('계약 체결(거래처 등록)', '계약 체결(거래처 등록)'), ('납품 관리', '납품 관리'), ('관계 유지', '관계 유지')], max_length=50, null=True, verbose_name='영업단계'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='myapi.company', verbose_name='회사ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(verbose_name='미팅 내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='report',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='사용품목'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('대면', '대면'), ('전화', '전화'), ('이메일', '이메일'), ('화상', '화상')], max_length=20, verbose_name='영업형태'),
        ),
        migrations.AlterField(
            model_name='report',
            name='visitDate',
            field=models.DateField(verbose_name='방문일자'),
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
    ]
