# Generated by Django 5.2.4 on 2025-10-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_alter_report_options_remove_company_company_code_sm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='company',
        ),
    ]
