# Generated by Django 5.2.4 on 2025-10-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_migrate_report_fields'),
        ('myapi', '0018_remove_report_company'),
    ]

    operations = [
    ]
