# Generated by Django 5.2.4 on 2025-10-30 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_merge_20251030_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='company_code',
            # Company 모델의 Primary Key가 company_code로 변경되었으므로 to_field 명시
            field=models.ForeignKey(blank=True, db_column='company_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_by_code', to='myapi.company', to_field='company_code', verbose_name='회사코드'),
        ),
    ]
