# Generated by Django 5.2.4 on 2025-10-31 01:21

from django.db import migrations, models


def remove_fields_safely(apps, schema_editor):
    """존재하는 필드만 안전하게 삭제 (Oracle 데이터베이스용)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Oracle에서 컬럼 존재 여부 확인 쿼리
        fields_to_remove = [
            'COMPANY_CODE_SM',
            'ID',
            'LOCATION',
            'MAIN_PRODUCT',
            'SALES_DIARY_COMPANY_CODE',
            'USERNAME',
        ]
        
        for column_name in fields_to_remove:
            try:
                # 컬럼이 존재하는지 확인
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_tab_columns 
                    WHERE table_name = 'COMPANIES' 
                    AND column_name = :col_name
                """, {'col_name': column_name})
                
                result = cursor.fetchone()
                if result and result[0] > 0:
                    # 컬럼이 존재하면 삭제
                    cursor.execute(f'ALTER TABLE "COMPANIES" DROP COLUMN "{column_name}"')
            except Exception as e:
                # 컬럼이 존재하지 않거나 이미 삭제된 경우 무시
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_remove_company_company_code_sm_remove_company_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_fields_safely,
            migrations.RunPython.noop,  # 역방향 마이그레이션은 아무것도 하지 않음
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='비밀번호 찾기 시 사용됩니다.', max_length=254, null=True, verbose_name='이메일'),
        ),
    ]
