# Generated by Django 5.2.4 on 2025-10-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_remove_company_company_code_sm_remove_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_changed',
            field=models.BooleanField(default=False, help_text='최초 로그인 후 비밀번호 변경 여부', verbose_name='비밀번호 변경 여부'),
        ),
    ]
