# Generated by Django 5.2.4 on 2025-11-04 00:12

import django.db.models.deletion
from django.db import migrations, models


def safe_remove_fields(apps, schema_editor):
    """존재하는 필드만 안전하게 삭제 (Oracle 데이터베이스용)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Company 모델의 필드들
        company_fields_to_remove = [
            'COMPANY_CODE_SM',
            'ID',
            'LOCATION',
            'MAIN_PRODUCT',
            'SALES_DIARY_COMPANY_CODE',
            'USERNAME',
        ]
        
        # Report 모델의 필드들
        report_fields_to_remove = [
            'COMPANY_OBJ_ID',
        ]
        
        # Company 테이블 필드 삭제
        for column_name in company_fields_to_remove:
            try:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_tab_columns 
                    WHERE table_name = 'COMPANIES' 
                    AND column_name = :col_name
                """, {'col_name': column_name})
                
                result = cursor.fetchone()
                if result and result[0] > 0:
                    cursor.execute(f'ALTER TABLE "COMPANIES" DROP COLUMN "{column_name}"')
            except Exception as e:
                print(f"컬럼 {column_name} 삭제 중 오류 (무시됨): {e}")
        
        # Report 테이블 필드 삭제
        for column_name in report_fields_to_remove:
            try:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_tab_columns 
                    WHERE table_name = 'REPORTS' 
                    AND column_name = :col_name
                """, {'col_name': column_name})
                
                result = cursor.fetchone()
                if result and result[0] > 0:
                    cursor.execute(f'ALTER TABLE "REPORTS" DROP COLUMN "{column_name}"')
            except Exception as e:
                print(f"컬럼 {column_name} 삭제 중 오류 (무시됨): {e}")


def reverse_safe_remove_fields(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


def safe_alter_financial_status(apps, schema_editor):
    """CompanyFinancialStatus의 company_id를 company_code로 안전하게 변경"""
    with schema_editor.connection.cursor() as cursor:
        try:
            # COMPANY_ID 컬럼이 존재하는지 확인
            cursor.execute("""
                SELECT COUNT(*) 
                FROM user_tab_columns 
                WHERE table_name = 'COMPANY_FINANCIAL_STATUS' 
                AND column_name = 'COMPANY_ID'
            """)
            exists = cursor.fetchone()[0] > 0
            
            if exists:
                # 기존 제약조건 삭제
                cursor.execute("""
                    SELECT constraint_name 
                    FROM user_constraints 
                    WHERE table_name = 'COMPANY_FINANCIAL_STATUS' 
                    AND constraint_type = 'R'
                    AND constraint_name LIKE '%COMPANY%'
                """)
                constraints = cursor.fetchall()
                for constraint in constraints:
                    try:
                        cursor.execute(f'ALTER TABLE "COMPANY_FINANCIAL_STATUS" DROP CONSTRAINT "{constraint[0]}"')
                    except Exception as e:
                        print(f"제약조건 삭제 중 오류 (무시됨): {e}")
                
                # 컬럼 타입 확인 및 변경
                cursor.execute("""
                    SELECT data_type 
                    FROM user_tab_columns 
                    WHERE table_name = 'COMPANY_FINANCIAL_STATUS' 
                    AND column_name = 'COMPANY_ID'
                """)
                col_type = cursor.fetchone()
                
                if col_type and col_type[0] != 'VARCHAR2':
                    # NUMBER 타입이면 VARCHAR2로 변경
                    # 먼저 임시 컬럼 생성
                    cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" ADD "COMPANY_CODE_TMP" VARCHAR2(50)')
                    
                    # 데이터 마이그레이션 (기존 ID를 문자열로 변환)
                    cursor.execute("""
                        UPDATE "COMPANY_FINANCIAL_STATUS" 
                        SET "COMPANY_CODE_TMP" = (
                            SELECT "COMPANY_CODE" 
                            FROM "COMPANIES" 
                            WHERE "COMPANIES"."ID" = "COMPANY_FINANCIAL_STATUS"."COMPANY_ID"
                        )
                    """)
                    
                    # 기존 컬럼 삭제
                    cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" DROP COLUMN "COMPANY_ID"')
                    
                    # 새 컬럼 이름 변경
                    cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" RENAME COLUMN "COMPANY_CODE_TMP" TO "COMPANY_CODE"')
                else:
                    # 이미 VARCHAR2 타입이면 이름만 변경
                    cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" RENAME COLUMN "COMPANY_ID" TO "COMPANY_CODE"')
                
                # 새 제약조건 추가
                cursor.execute("""
                    ALTER TABLE "COMPANY_FINANCIAL_STATUS" 
                    ADD CONSTRAINT "COMPANY_F_COMPANY_C_8063ADE5_F" 
                    FOREIGN KEY ("COMPANY_CODE") 
                    REFERENCES "COMPANIES" ("COMPANY_CODE") 
                    DEFERRABLE INITIALLY DEFERRED
                """)
        except Exception as e:
            print(f"CompanyFinancialStatus 변경 중 오류: {e}")


def reverse_safe_alter_financial_status(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


def safe_alter_sales_data_company(apps, schema_editor):
    """SalesData의 company_obj_id를 company_code_id로 안전하게 변경 (타입 변경 포함)"""
    with schema_editor.connection.cursor() as cursor:
        try:
            # COMPANY_OBJ_ID 컬럼이 존재하는지 확인
            cursor.execute("""
                SELECT COUNT(*) 
                FROM user_tab_columns 
                WHERE table_name = 'SALES_DATA' 
                AND column_name = 'COMPANY_OBJ_ID'
            """)
            exists = cursor.fetchone()[0] > 0
            
            if exists:
                # 기존 제약조건 삭제
                cursor.execute("""
                    SELECT constraint_name 
                    FROM user_constraints 
                    WHERE table_name = 'SALES_DATA' 
                    AND constraint_type = 'R'
                    AND constraint_name LIKE '%COMPANY%'
                """)
                constraints = cursor.fetchall()
                for constraint in constraints:
                    try:
                        cursor.execute(f'ALTER TABLE "SALES_DATA" DROP CONSTRAINT "{constraint[0]}"')
                    except Exception as e:
                        print(f"제약조건 삭제 중 오류 (무시됨): {e}")
                
                # 컬럼 타입 확인
                cursor.execute("""
                    SELECT data_type 
                    FROM user_tab_columns 
                    WHERE table_name = 'SALES_DATA' 
                    AND column_name = 'COMPANY_OBJ_ID'
                """)
                col_type = cursor.fetchone()
                
                if col_type and col_type[0] != 'VARCHAR2':
                    # NUMBER 타입이면 VARCHAR2로 변경
                    # 임시 컬럼 생성
                    cursor.execute('ALTER TABLE "SALES_DATA" ADD "COMPANY_CODE_ID_TMP" VARCHAR2(50)')
                    
                    # 데이터 마이그레이션 (기존 ID를 company_code 문자열로 변환)
                    cursor.execute("""
                        UPDATE "SALES_DATA" 
                        SET "COMPANY_CODE_ID_TMP" = (
                            SELECT "COMPANY_CODE" 
                            FROM "COMPANIES" 
                            WHERE "COMPANIES"."ID" = "SALES_DATA"."COMPANY_OBJ_ID"
                        )
                    """)
                    
                    # 기존 컬럼 삭제
                    cursor.execute('ALTER TABLE "SALES_DATA" DROP COLUMN "COMPANY_OBJ_ID"')
                    
                    # 새 컬럼 이름 변경
                    cursor.execute('ALTER TABLE "SALES_DATA" RENAME COLUMN "COMPANY_CODE_ID_TMP" TO "COMPANY_CODE_ID"')
                else:
                    # 이미 VARCHAR2 타입이면 이름만 변경
                    cursor.execute('ALTER TABLE "SALES_DATA" RENAME COLUMN "COMPANY_OBJ_ID" TO "COMPANY_CODE_ID"')
                
                # 새 제약조건 추가
                cursor.execute("""
                    ALTER TABLE "SALES_DATA" 
                    ADD CONSTRAINT "SALES_DAT_COMPANY_C_812D16D1_F" 
                    FOREIGN KEY ("COMPANY_CODE_ID") 
                    REFERENCES "COMPANIES" ("COMPANY_CODE") 
                    DEFERRABLE INITIALLY DEFERRED
                """)
        except Exception as e:
            print(f"SalesData company_obj 변경 중 오류: {e}")


def reverse_safe_alter_sales_data_company(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


def safe_alter_report_columns(apps, schema_editor):
    """Report 모델의 컬럼명 변경 (visitDate -> visit_date, createdAt -> created_at)"""
    with schema_editor.connection.cursor() as cursor:
        try:
            # VISITDATE를 VISIT_DATE로 변경
            cursor.execute("""
                SELECT COUNT(*) 
                FROM user_tab_columns 
                WHERE table_name = 'REPORTS' 
                AND column_name = 'VISITDATE'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_tab_columns 
                    WHERE table_name = 'REPORTS' 
                    AND column_name = 'VISIT_DATE'
                """)
                if cursor.fetchone()[0] == 0:
                    cursor.execute('ALTER TABLE "REPORTS" RENAME COLUMN "VISITDATE" TO "VISIT_DATE"')
            
            # CREATEDAT를 CREATED_AT으로 변경
            cursor.execute("""
                SELECT COUNT(*) 
                FROM user_tab_columns 
                WHERE table_name = 'REPORTS' 
                AND column_name = 'CREATEDAT'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_tab_columns 
                    WHERE table_name = 'REPORTS' 
                    AND column_name = 'CREATED_AT'
                """)
                if cursor.fetchone()[0] == 0:
                    cursor.execute('ALTER TABLE "REPORTS" RENAME COLUMN "CREATEDAT" TO "CREATED_AT"')
        except Exception as e:
            print(f"Report 컬럼명 변경 중 오류: {e}")


def reverse_safe_alter_report_columns(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


def safe_alter_sales_data_columns(apps, schema_editor):
    """SalesData 모델의 한글 컬럼명을 영문으로 변경"""
    with schema_editor.connection.cursor() as cursor:
        try:
            # 한글 컬럼명과 영문 컬럼명 매핑
            column_mappings = [
                ('BL번호', 'BL_NUMBER'),
                ('Box', 'BOX'),
                ('거래처명', 'CUSTOMER_NAME'),
                ('담당자', 'MANAGER'),
                ('등급', 'GRADE'),
                ('매입금액', 'PURCHASE_AMOUNT'),
                ('매입단가', 'PURCHASE_UNIT_PRICE'),
                ('매입비고', 'PURCHASE_NOTE'),
                ('매입일자', 'PURCHASE_DATE'),
                ('매입처', 'PURCHASE_SOURCE'),
                ('매출금액', 'SALE_AMOUNT'),
                ('매출단가', 'SALE_UNIT_PRICE'),
                ('매출담당자', 'SALES_PERSON'),
                ('매출부서', 'SALES_DEPT'),
                ('매출비고', 'SALE_NOTE'),
                ('매출이익', 'SALE_PROFIT'),
                ('매출일자', 'SALE_DATE'),
                ('부위', 'CUT_TYPE'),
                ('브랜드', 'BRAND'),
                ('상품명', 'PRODUCT_NAME'),
                ('상품코드', 'PRODUCT_CODE'),
                ('수입로컬', 'IMPORT_LOCAL'),
                ('원산지', 'ORIGIN'),
                ('원산지_축종', 'ORIGIN_LIVESTOCK'),
                ('유통형태', 'DISTRIBUTION_TYPE'),
                ('이관재고여부', 'TRANSFER_INVENTORY_YN'),
                ('이력번호', 'HISTORY_NO'),
                ('이익율', 'PROFIT_RATE'),
                ('재고보유일', 'INVENTORY_DAYS'),
                ('중량_Kg', 'WEIGHT_KG'),
                ('지점명', 'BRANCH_NAME'),
                ('축종', 'LIVESTOCK_TYPE'),
                ('축종_부위', 'LIVESTOCK_CUT'),
                ('코드', 'CODE'),
            ]
            
            for old_name, new_name in column_mappings:
                try:
                    # 기존 컬럼이 존재하고 새 컬럼이 없을 때만 변경
                    cursor.execute(f"""
                        SELECT COUNT(*) 
                        FROM user_tab_columns 
                        WHERE table_name = 'SALES_DATA' 
                        AND column_name = :old_name
                    """, {'old_name': old_name})
                    if cursor.fetchone()[0] > 0:
                        cursor.execute(f"""
                            SELECT COUNT(*) 
                            FROM user_tab_columns 
                            WHERE table_name = 'SALES_DATA' 
                            AND column_name = :new_name
                        """, {'new_name': new_name})
                        if cursor.fetchone()[0] == 0:
                            cursor.execute(f'ALTER TABLE "SALES_DATA" RENAME COLUMN "{old_name}" TO "{new_name}"')
                except Exception as e:
                    print(f"컬럼 {old_name} -> {new_name} 변경 중 오류 (무시됨): {e}")
        except Exception as e:
            print(f"SalesData 컬럼명 변경 중 오류: {e}")


def reverse_safe_alter_sales_data_columns(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_remove_company_company_code_sm_remove_company_id_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_remove_fields, reverse_safe_remove_fields),
        migrations.RunPython(safe_alter_financial_status, reverse_safe_alter_financial_status),
        migrations.RunPython(safe_alter_sales_data_company, reverse_safe_alter_sales_data_company),
        migrations.RunPython(safe_alter_report_columns, reverse_safe_alter_report_columns),
        migrations.RunPython(safe_alter_sales_data_columns, reverse_safe_alter_sales_data_columns),
        # RemoveField 작업은 RunPython에서 이미 처리했으므로 제거
        # Django 모델 상태만 업데이트하기 위해 SeparateDatabaseAndState 사용
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스 작업은 RunPython에서 이미 처리됨
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='company',
                    name='company_code_sm',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='location',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='main_product',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='sales_diary_company_code',
                ),
                migrations.RemoveField(
                    model_name='company',
                    name='username',
                ),
                migrations.RemoveField(
                    model_name='report',
                    name='company_obj',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스 작업은 RunPython에서 이미 처리됨
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='companyfinancialstatus',
                    name='company',
                    field=models.ForeignKey(db_column='company_code', on_delete=django.db.models.deletion.CASCADE, related_name='financial_statuses', to='myapi.company', verbose_name='회사'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스 작업은 RunPython에서 이미 처리됨
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='report',
                    name='company_code',
                    field=models.ForeignKey(blank=True, db_column='company_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='myapi.company', verbose_name='회사코드'),
                ),
                migrations.AlterField(
                    model_name='report',
                    name='createdAt',
                    field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='작성일'),
                ),
                migrations.AlterField(
                    model_name='report',
                    name='visitDate',
                    field=models.DateField(db_column='visit_date', verbose_name='방문일자'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스 작업은 RunPython에서 이미 처리됨
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='salesdata',
                    name='BL번호',
                    field=models.CharField(blank=True, db_column='bl_number', max_length=100, null=True, verbose_name='B/L번호(도체번호)'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='Box',
                    field=models.IntegerField(blank=True, db_column='box', null=True, verbose_name='Box'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스 작업은 RunPython에서 이미 처리됨
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='salesdata',
                    name='company_obj',
                    field=models.ForeignKey(blank=True, db_column='company_code_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_data', to='myapi.company', verbose_name='연결된 회사'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스 작업은 RunPython에서 이미 처리됨
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='salesdata',
                    name='BL번호',
                    field=models.CharField(blank=True, db_column='bl_number', max_length=100, null=True, verbose_name='B/L번호(도체번호)'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='Box',
                    field=models.IntegerField(blank=True, db_column='box', null=True, verbose_name='Box'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='거래처명',
                    field=models.CharField(db_column='customer_name', max_length=200, verbose_name='거래처명'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='담당자',
                    field=models.CharField(blank=True, db_column='manager', max_length=100, null=True, verbose_name='담당자'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='등급',
                    field=models.CharField(blank=True, db_column='grade', max_length=50, null=True, verbose_name='등급'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매입금액',
                    field=models.BigIntegerField(blank=True, db_column='purchase_amount', null=True, verbose_name='매입금액'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매입단가',
                    field=models.IntegerField(blank=True, db_column='purchase_unit_price', null=True, verbose_name='매입단가'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매입비고',
                    field=models.TextField(blank=True, db_column='purchase_note', null=True, verbose_name='매입비고'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매입일자',
                    field=models.DateField(blank=True, db_column='purchase_date', null=True, verbose_name='매입일자'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매입처',
                    field=models.CharField(blank=True, db_column='purchase_source', max_length=200, null=True, verbose_name='매입 처'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출금액',
                    field=models.BigIntegerField(db_column='sale_amount', verbose_name='매출금액'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출단가',
                    field=models.IntegerField(blank=True, db_column='sale_unit_price', null=True, verbose_name='매출단가'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출담당자',
                    field=models.CharField(blank=True, db_column='sales_person', max_length=100, null=True, verbose_name='매출담당자'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출부서',
                    field=models.CharField(blank=True, db_column='sales_dept', max_length=100, null=True, verbose_name='매출부서'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출비고',
                    field=models.TextField(blank=True, db_column='sale_note', null=True, verbose_name='매출비고'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출이익',
                    field=models.BigIntegerField(blank=True, db_column='sale_profit', null=True, verbose_name='매출이익'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='매출일자',
                    field=models.DateField(db_column='sale_date', verbose_name='매출일자'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='부위',
                    field=models.CharField(blank=True, db_column='cut_type', max_length=100, null=True, verbose_name='부위'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='브랜드',
                    field=models.CharField(blank=True, db_column='brand', max_length=100, null=True, verbose_name='브랜드'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='상품명',
                    field=models.CharField(blank=True, db_column='product_name', max_length=200, null=True, verbose_name='상품명'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='상품코드',
                    field=models.CharField(blank=True, db_column='product_code', max_length=100, null=True, verbose_name='상품코드'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='수입로컬',
                    field=models.CharField(blank=True, db_column='import_local', max_length=20, null=True, verbose_name='수입/로컬'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='원산지',
                    field=models.CharField(blank=True, db_column='origin', max_length=100, null=True, verbose_name='원산지'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='원산지_축종',
                    field=models.CharField(blank=True, db_column='origin_livestock', max_length=100, null=True, verbose_name='원산지'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='유통형태',
                    field=models.CharField(blank=True, db_column='distribution_type', max_length=100, null=True, verbose_name='유통형태'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='이관재고여부',
                    field=models.CharField(blank=True, db_column='transfer_inventory_yn', max_length=20, null=True, verbose_name='이관재고 여부'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='이력번호',
                    field=models.CharField(blank=True, db_column='history_no', max_length=100, null=True, verbose_name='이력번호'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='이익율',
                    field=models.FloatField(blank=True, db_column='profit_rate', null=True, verbose_name='이익율'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='재고보유일',
                    field=models.IntegerField(blank=True, db_column='inventory_days', null=True, verbose_name='재고보유일'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='중량_Kg',
                    field=models.FloatField(blank=True, db_column='weight_kg', null=True, verbose_name='중량(Kg)'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='지점명',
                    field=models.CharField(blank=True, db_column='branch_name', max_length=100, null=True, verbose_name='지점명'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='축종',
                    field=models.CharField(blank=True, db_column='livestock_type', max_length=100, null=True, verbose_name='축종'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='축종_부위',
                    field=models.CharField(blank=True, db_column='livestock_cut', max_length=100, null=True, verbose_name='축종-부위'),
                ),
                migrations.AlterField(
                    model_name='salesdata',
                    name='코드',
                    field=models.CharField(blank=True, db_column='code', max_length=50, null=True, verbose_name='코드'),
                ),
            ],
        ),
    ]
