# Generated by Django 5.2.4 on 2025-11-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_remove_company_company_code_sm_remove_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='중량_Kg',
            field=models.FloatField(blank=True, db_column='WEIGHT_KG', null=True, verbose_name='중량(Kg)'),
        ),
    ]
