# Generated by Django 5.2.4 on 2025-11-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_alter_salesdata_중량_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='company_obj',
        ),
    ]
