# Generated by Django 5.2.4 on 2025-11-05 02:38

from django.db import migrations


def fix_company_code_type(apps, schema_editor):
    """COMPANY_FINANCIAL_STATUS 테이블의 COMPANY_CODE 컬럼을 NUMBER에서 NVARCHAR2로 변경"""
    with schema_editor.connection.cursor() as cursor:
        try:
            # COMPANY_CODE 컬럼의 타입 확인
            cursor.execute("""
                SELECT data_type 
                FROM user_tab_columns 
                WHERE table_name = 'COMPANY_FINANCIAL_STATUS' 
                AND column_name = 'COMPANY_CODE'
            """)
            col_type_result = cursor.fetchone()
            
            if col_type_result:
                current_type = col_type_result[0]
                
                # 기존 외래키 제약조건 삭제 (있다면)
                cursor.execute("""
                    SELECT constraint_name 
                    FROM user_constraints 
                    WHERE table_name = 'COMPANY_FINANCIAL_STATUS' 
                    AND constraint_type = 'R'
                    AND constraint_name LIKE '%COMPANY%'
                """)
                constraints = cursor.fetchall()
                for constraint in constraints:
                    try:
                        cursor.execute(f'ALTER TABLE "COMPANY_FINANCIAL_STATUS" DROP CONSTRAINT "{constraint[0]}"')
                    except Exception as e:
                        print(f"제약조건 삭제 중 오류 (무시됨): {e}")
                
                # NVARCHAR2가 아니면 변경 필요
                if current_type != 'NVARCHAR2':
                    # 기존 데이터 확인
                    cursor.execute('SELECT COUNT(*) FROM "COMPANY_FINANCIAL_STATUS"')
                    record_count = cursor.fetchone()[0]
                    
                    if record_count > 0:
                        # 데이터가 있으면 먼저 임시 컬럼 생성 (NVARCHAR2로 생성하여 COMPANIES.COMPANY_CODE와 타입 일치)
                        cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" ADD "COMPANY_CODE_TMP" NVARCHAR2(100)')
                        
                        # 데이터 복사 (VARCHAR2 -> NVARCHAR2는 직접 복사 가능)
                        cursor.execute('UPDATE "COMPANY_FINANCIAL_STATUS" SET "COMPANY_CODE_TMP" = "COMPANY_CODE"')
                        
                        # 기존 컬럼 삭제
                        cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" DROP COLUMN "COMPANY_CODE"')
                        
                        # 새 컬럼 이름 변경
                        cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" RENAME COLUMN "COMPANY_CODE_TMP" TO "COMPANY_CODE"')
                        
                        # NOT NULL 제약조건 추가
                        cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" MODIFY "COMPANY_CODE" NOT NULL')
                    else:
                        # 데이터가 없으면 직접 변경 (NVARCHAR2로 생성하여 COMPANIES.COMPANY_CODE와 타입 일치)
                        cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" DROP COLUMN "COMPANY_CODE"')
                        cursor.execute('ALTER TABLE "COMPANY_FINANCIAL_STATUS" ADD "COMPANY_CODE" NVARCHAR2(100) NOT NULL')
                    
                    print(f"COMPANY_CODE 컬럼을 {current_type}에서 NVARCHAR2(100)로 변경 완료")
                else:
                    print("COMPANY_CODE 컬럼이 이미 NVARCHAR2 타입입니다.")
                
                # 외래키 제약조건 추가 시도 (COMPANIES.COMPANY_CODE가 UNIQUE 제약조건이 있는 경우에만 가능)
                # 현재 COMPANIES 테이블의 기본 키가 ID이므로 외래키 제약조건 추가는 건너뜀
                # Django ORM은 to_field를 통해 자동으로 처리하므로 DB 레벨 외래키 제약조건이 없어도 작동함
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM user_constraints 
                    WHERE table_name = 'COMPANIES' 
                    AND constraint_type = 'U'
                    AND constraint_name IN (
                        SELECT constraint_name 
                        FROM user_cons_columns 
                        WHERE table_name = 'COMPANIES' 
                        AND column_name = 'COMPANY_CODE'
                    )
                """)
                has_unique = cursor.fetchone()[0] > 0
                
                if has_unique:
                    cursor.execute("""
                        SELECT COUNT(*) 
                        FROM user_constraints 
                        WHERE table_name = 'COMPANY_FINANCIAL_STATUS' 
                        AND constraint_type = 'R'
                        AND constraint_name LIKE '%COMPANY%'
                    """)
                    has_fk = cursor.fetchone()[0] > 0
                    
                    if not has_fk:
                        try:
                            cursor.execute("""
                                ALTER TABLE "COMPANY_FINANCIAL_STATUS" 
                                ADD CONSTRAINT "COMPANY_F_COMPANY_C_8063ADE5_F" 
                                FOREIGN KEY ("COMPANY_CODE") 
                                REFERENCES "COMPANIES" ("COMPANY_CODE") 
                                DEFERRABLE INITIALLY DEFERRED
                            """)
                            print("외래키 제약조건 추가 완료")
                        except Exception as fk_error:
                            print(f"외래키 제약조건 추가 실패 (무시됨): {fk_error}")
                            print("Django ORM의 to_field를 통해 관계가 처리됩니다.")
                else:
                    print("COMPANIES.COMPANY_CODE에 UNIQUE 제약조건이 없어 외래키 제약조건을 추가할 수 없습니다.")
                    print("Django ORM의 to_field를 통해 관계가 처리됩니다.")
            else:
                print("COMPANY_CODE 컬럼을 찾을 수 없습니다.")
        except Exception as e:
            print(f"CompanyFinancialStatus 변경 중 오류: {e}")
            raise


def reverse_fix_company_code_type(apps, schema_editor):
    """역방향 마이그레이션은 스킵"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_remove_company_obj_from_sales_data'),
    ]

    operations = [
        migrations.RunPython(fix_company_code_type, reverse_fix_company_code_type),
    ]
