# Generated by Django 5.2.4 on 2025-11-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_fix_reports_company_code_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customer_classification',
            field=models.CharField(blank=True, choices=[('잠재', '잠재'), ('신규', '신규'), ('기존', '기존'), ('이탈', '이탈'), ('벤더', '벤더')], max_length=50, null=True, verbose_name='고객분류'),
        ),
    ]
