# Generated by Django 5.2.4 on 2025-11-20 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_add_viewer_role_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='사용자명')),
                ('action_type', models.CharField(choices=[('login', '로그인'), ('logout', '로그아웃'), ('permission_change', '권한 변경'), ('personal_info_access', '개인정보 접근'), ('download', '다운로드')], max_length=50, verbose_name='액션 타입')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('old_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='이전 값')),
                ('new_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='새 값')),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='리소스 타입')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='리소스 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일시')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='대상 사용자')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그들',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'), models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action_type', '-created_at'], name='audit_logs_action__a429dc_idx')],
            },
        ),
    ]
