# Generated by Django 5.2.4 on 2025-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='인허가정보')),
                ('company_name', models.CharField(max_length=200, verbose_name='업체명')),
                ('industry', models.CharField(choices=[('축산물 가공장', '축산물 가공장'), ('식품 가공장', '식품 가공장'), ('도소매', '도소매')], max_length=50, verbose_name='업종')),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='소재지')),
                ('main_products', models.TextField(blank=True, null=True, verbose_name='주요제품')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('priority', models.CharField(blank=True, choices=[('높음', '높음'), ('중간', '중간'), ('낮음', '낮음')], max_length=10, null=True, verbose_name='우선순위')),
                ('has_transaction', models.CharField(blank=True, choices=[('거래중', '거래중'), ('미거래', '미거래')], max_length=10, null=True, verbose_name='자사거래')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '업체 리스트',
                'verbose_name_plural': '업체 리스트들',
                'db_table': 'prospect_companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
