# Generated by Django 5.2.4 on 2026-02-27 01:45
# 재작성: 부분 실행 후 ORA-00904(컬럼 없음) 오류 방지를 위해
# SeparateDatabaseAndState 패턴 적용 - 이미 삭제된 컬럼은 무시

from django.db import migrations, models


def drop_columns_safely(apps, schema_editor):
    """
    SALES_DATA, COMPANIES 테이블에서 불필요한 컬럼을 삭제.
    이미 삭제된 컬럼(ORA-00904)이나 없는 테이블(ORA-00942)은 무시.
    """
    connection = schema_editor.connection

    drops = [
        # COMPANIES 테이블
        ('COMPANIES', 'BIZ_NAME'),
        ('COMPANIES', 'CODE_CREATE_DATE'),
        ('COMPANIES', 'COMPANY_CODE_SAP'),
        ('COMPANIES', 'DEPARTMENT'),
        ('COMPANIES', 'SAP_CODE_TYPE'),
        # SALES_DATA 테이블
        ('SALES_DATA', 'BL_NUMBER'),
        ('SALES_DATA', 'BOX'),
        ('SALES_DATA', 'MANAGER'),
        ('SALES_DATA', 'GRADE'),
        ('SALES_DATA', 'PURCHASE_AMOUNT'),
        ('SALES_DATA', 'PURCHASE_UNIT_PRICE'),
        ('SALES_DATA', 'PURCHASE_NOTE'),
        ('SALES_DATA', 'PURCHASE_DATE'),
        ('SALES_DATA', 'PURCHASE_SOURCE'),
        ('SALES_DATA', 'SALE_UNIT_PRICE'),
        ('SALES_DATA', 'SALES_PERSON'),
        ('SALES_DATA', 'SALES_DEPT'),
        ('SALES_DATA', 'SALE_NOTE'),
        ('SALES_DATA', 'SALE_PROFIT'),
        ('SALES_DATA', 'CUT_TYPE'),
        ('SALES_DATA', 'BRAND'),
        ('SALES_DATA', 'PRODUCT_NAME'),
        ('SALES_DATA', 'PRODUCT_CODE'),
        ('SALES_DATA', 'IMPORT_LOCAL'),
        ('SALES_DATA', 'ORIGIN'),
        ('SALES_DATA', 'ORIGIN_LIVESTOCK'),
        ('SALES_DATA', 'DISTRIBUTION_TYPE'),
        ('SALES_DATA', 'TRANSFER_INVENTORY_YN'),
        ('SALES_DATA', 'HISTORY_NO'),
        ('SALES_DATA', 'PROFIT_RATE'),
        ('SALES_DATA', 'INVENTORY_DAYS'),
        ('SALES_DATA', 'WEIGHT_KG'),
        ('SALES_DATA', 'BRANCH_NAME'),
        ('SALES_DATA', 'LIVESTOCK_TYPE'),
        ('SALES_DATA', 'LIVESTOCK_CUT'),
    ]

    with connection.cursor() as cursor:
        for table, column in drops:
            try:
                cursor.execute(f'ALTER TABLE "{table}" DROP COLUMN "{column}"')
            except Exception:
                pass  # 이미 삭제된 컬럼이거나 존재하지 않으면 무시


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_prospectcompany'),
    ]

    operations = [
        # DROP: DB는 에러 무시 함수, Django 상태는 정상 RemoveField
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_columns_safely, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(model_name='company', name='biz_name'),
                migrations.RemoveField(model_name='company', name='code_create_date'),
                migrations.RemoveField(model_name='company', name='company_code_sap'),
                migrations.RemoveField(model_name='company', name='department'),
                migrations.RemoveField(model_name='company', name='sap_code_type'),
                migrations.RemoveField(model_name='salesdata', name='BL번호'),
                migrations.RemoveField(model_name='salesdata', name='Box'),
                migrations.RemoveField(model_name='salesdata', name='담당자'),
                migrations.RemoveField(model_name='salesdata', name='등급'),
                migrations.RemoveField(model_name='salesdata', name='매입금액'),
                migrations.RemoveField(model_name='salesdata', name='매입단가'),
                migrations.RemoveField(model_name='salesdata', name='매입비고'),
                migrations.RemoveField(model_name='salesdata', name='매입일자'),
                migrations.RemoveField(model_name='salesdata', name='매입처'),
                migrations.RemoveField(model_name='salesdata', name='매출단가'),
                migrations.RemoveField(model_name='salesdata', name='매출담당자'),
                migrations.RemoveField(model_name='salesdata', name='매출부서'),
                migrations.RemoveField(model_name='salesdata', name='매출비고'),
                migrations.RemoveField(model_name='salesdata', name='매출이익'),
                migrations.RemoveField(model_name='salesdata', name='부위'),
                migrations.RemoveField(model_name='salesdata', name='브랜드'),
                migrations.RemoveField(model_name='salesdata', name='상품명'),
                migrations.RemoveField(model_name='salesdata', name='상품코드'),
                migrations.RemoveField(model_name='salesdata', name='수입로컬'),
                migrations.RemoveField(model_name='salesdata', name='원산지'),
                migrations.RemoveField(model_name='salesdata', name='원산지_축종'),
                migrations.RemoveField(model_name='salesdata', name='유통형태'),
                migrations.RemoveField(model_name='salesdata', name='이관재고여부'),
                migrations.RemoveField(model_name='salesdata', name='이력번호'),
                migrations.RemoveField(model_name='salesdata', name='이익율'),
                migrations.RemoveField(model_name='salesdata', name='재고보유일'),
                migrations.RemoveField(model_name='salesdata', name='중량_Kg'),
                migrations.RemoveField(model_name='salesdata', name='지점명'),
                migrations.RemoveField(model_name='salesdata', name='축종'),
                migrations.RemoveField(model_name='salesdata', name='축종_부위'),
            ],
        ),

        # ADD: Company 신규 필드
        migrations.AddField(
            model_name='company',
            name='company_code_erp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ERP거래처코드'),
        ),
        migrations.AddField(
            model_name='company',
            name='erp_code_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ERP코드여부'),
        ),
        migrations.AddField(
            model_name='company',
            name='purchase_unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='매입단가'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='등록일자'),
        ),
        migrations.AddField(
            model_name='company',
            name='sale_unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='매출단가'),
        ),

        # ADD: SalesData 신규 필드
        migrations.AddField(
            model_name='salesdata',
            name='거래처약칭',
            field=models.CharField(blank=True, db_column='customer_abbr', max_length=200, null=True, verbose_name='거래처약칭'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='건수',
            field=models.IntegerField(blank=True, db_column='count', null=True, verbose_name='건수'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='공급가액',
            field=models.BigIntegerField(blank=True, db_column='supply_amount', null=True, verbose_name='공급가액'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='규격',
            field=models.CharField(blank=True, db_column='spec', max_length=50, null=True, verbose_name='규격'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='단위',
            field=models.CharField(blank=True, db_column='unit', max_length=20, null=True, verbose_name='단위'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='보관방법',
            field=models.CharField(blank=True, db_column='storage_method', max_length=100, null=True, verbose_name='보관방법'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='부가세액',
            field=models.BigIntegerField(blank=True, db_column='vat_amount', null=True, verbose_name='부가세액'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='소비기간',
            field=models.CharField(blank=True, db_column='consumption_period', max_length=50, null=True, verbose_name='소비기간'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='수량',
            field=models.FloatField(blank=True, db_column='quantity', null=True, verbose_name='수량'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='중량',
            field=models.FloatField(blank=True, db_column='weight', null=True, verbose_name='중량'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='출고단가',
            field=models.IntegerField(blank=True, db_column='ship_unit_price', null=True, verbose_name='출고단가'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='품목명칭',
            field=models.CharField(blank=True, db_column='item_name', max_length=200, null=True, verbose_name='품목명칭'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='품목약칭',
            field=models.CharField(blank=True, db_column='item_abbr', max_length=200, null=True, verbose_name='품목약칭'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='품목코드',
            field=models.CharField(blank=True, db_column='item_code', max_length=100, null=True, verbose_name='품목코드'),
        ),

        # ALTER: 기존 필드 변경
        migrations.AlterField(
            model_name='salesdata',
            name='매출금액',
            field=models.BigIntegerField(db_column='sale_amount', verbose_name='합계금액'),
        ),
    ]
